apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: v11.1
  template:
    metadata:
      labels:
        app: vote-bot
        version: v11.1
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivoto:80
        image: docker.l5d.io/buoyantio/emojivoto-web:v11.1
        name: vote-bot
        resources:
          requests:
            cpu: 10m
